### ISSUE TITLE
HDFS failures during cluster restart

### ISSUE THREAD

**Issue by jmaron** [hortonworks/structor#5] opened 2014-07-22 20:11 UTC
the HDFS data and namenode dirs appear to be configured to sub-directories of /var/run.  It seems that those are temp directories - halting and restarting the cluster triggers HDFS errors requiring reformatiing (at least that is my experience).  May be a good idea to change those values..

**Comment by omalley** [comment] 2015-09-01 15:43
This is a duplicate of #18.

**Closed by omalley** 2015-09-01 15:43 UTC
